// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: UIDseign

#include "../ui.h"

void ui_DashboardScreen_screen_init(void)
{
    ui_DashboardScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_DashboardScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DashboardScreen, lv_color_hex(0xD3B7B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashboardScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsButton = lv_button_create(ui_DashboardScreen);
    lv_obj_set_width(ui_SettingsButton, 100);
    lv_obj_set_height(ui_SettingsButton, 50);
    lv_obj_set_x(ui_SettingsButton, 0);
    lv_obj_set_y(ui_SettingsButton, -10);
    lv_obj_set_align(ui_SettingsButton, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_SettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SettingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_SettingsButton);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Settings");

    ui_resultTable = lv_obj_create(ui_DashboardScreen);
    lv_obj_remove_style_all(ui_resultTable);
    lv_obj_set_width(ui_resultTable, 252);
    lv_obj_set_height(ui_resultTable, 250);
    lv_obj_set_x(ui_resultTable, 0);
    lv_obj_set_y(ui_resultTable, 20);
    lv_obj_set_align(ui_resultTable, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_resultTable, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_resultTable, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_resultTable, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_header1 = lv_label_create(ui_resultTable);
    lv_obj_set_width(ui_header1, 60);
    lv_obj_set_height(ui_header1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_header1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_header1, "Record");
    lv_obj_set_style_border_color(ui_header1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_header1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_header1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_header1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_header1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_header1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_header1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header2 = lv_label_create(ui_resultTable);
    lv_obj_set_width(ui_header2, 62);
    lv_obj_set_height(ui_header2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_header2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_header2, "Time");
    lv_obj_set_style_border_color(ui_header2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_header2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_header2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_header2, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header3 = lv_label_create(ui_resultTable);
    lv_obj_set_width(ui_header3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_header3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_header3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_header3, "Prediction Result");
    lv_obj_set_style_border_color(ui_header3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_header3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_header3, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_header3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_header3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_header3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_header3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tablerow = lv_obj_create(ui_resultTable);
    lv_obj_remove_style_all(ui_tablerow);
    lv_obj_set_width(ui_tablerow, 252);
    lv_obj_set_height(ui_tablerow, 50);
    lv_obj_set_align(ui_tablerow, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tablerow, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_tablerow, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_tablerow, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rowcl1 = lv_label_create(ui_tablerow);
    lv_obj_set_width(ui_rowcl1, 60);
    lv_obj_set_height(ui_rowcl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rowcl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rowcl1, "Non");
    lv_obj_set_style_border_color(ui_rowcl1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rowcl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rowcl1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rowcl1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_rowcl1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_rowcl1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_rowcl1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_rowcl1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rowcl2 = lv_label_create(ui_tablerow);
    lv_obj_set_width(ui_rowcl2, 62);
    lv_obj_set_height(ui_rowcl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rowcl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rowcl2, "Non");
    lv_obj_set_style_border_color(ui_rowcl2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rowcl2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rowcl2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rowcl2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_rowcl2, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_rowcl2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_rowcl2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_rowcl2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rowcl3 = lv_label_create(ui_tablerow);
    lv_obj_set_width(ui_rowcl3, 129);
    lv_obj_set_height(ui_rowcl3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rowcl3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rowcl3, "Non");
    lv_obj_set_style_border_color(ui_rowcl3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rowcl3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rowcl3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rowcl3, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_rowcl3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_rowcl3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_rowcl3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_rowcl3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SettingsButton, ui_event_SettingsButton, LV_EVENT_ALL, NULL);

}
