// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: UIDseign

#include "../ui.h"

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsScreen, lv_color_hex(0xD3B7B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 350);
    lv_obj_set_height(ui_Container6, 300);
    lv_obj_set_x(ui_Container6, 0);
    lv_obj_set_y(ui_Container6, 30);
    lv_obj_set_align(ui_Container6, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AppPasswordLabel = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_AppPasswordLabel, 120);
    lv_obj_set_height(ui_AppPasswordLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AppPasswordLabel, -100);
    lv_obj_set_y(ui_AppPasswordLabel, -101);
    lv_obj_set_align(ui_AppPasswordLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AppPasswordLabel, "App Password:");
    lv_obj_set_style_pad_left(ui_AppPasswordLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AppPasswordLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AppPasswordLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AppPasswordLabel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AppPasswordText = lv_textarea_create(ui_Container6);
    lv_obj_set_width(ui_AppPasswordText, 220);
    lv_obj_set_height(ui_AppPasswordText, 20);
    lv_obj_set_x(ui_AppPasswordText, 68);
    lv_obj_set_y(ui_AppPasswordText, -132);
    lv_obj_set_align(ui_AppPasswordText, LV_ALIGN_CENTER);

    ui_Parent1Phone = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Parent1Phone, 120);
    lv_obj_set_height(ui_Parent1Phone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Parent1Phone, -294);
    lv_obj_set_y(ui_Parent1Phone, 114);
    lv_obj_set_align(ui_Parent1Phone, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Parent1Phone, "Parent 1 Phone:");
    lv_obj_set_style_pad_left(ui_Parent1Phone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Parent1Phone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Parent1Phone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Parent1Phone, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Parent1PhoneText = lv_textarea_create(ui_Container6);
    lv_obj_set_width(ui_Parent1PhoneText, 220);
    lv_obj_set_height(ui_Parent1PhoneText, 20);
    lv_obj_set_x(ui_Parent1PhoneText, 68);
    lv_obj_set_y(ui_Parent1PhoneText, -132);
    lv_obj_set_align(ui_Parent1PhoneText, LV_ALIGN_CENTER);

    ui_Parent2Phone = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Parent2Phone, 120);
    lv_obj_set_height(ui_Parent2Phone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Parent2Phone, -294);
    lv_obj_set_y(ui_Parent2Phone, 114);
    lv_obj_set_align(ui_Parent2Phone, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Parent2Phone, "Parent 1 Phone:");
    lv_obj_set_style_pad_left(ui_Parent2Phone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Parent2Phone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Parent2Phone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Parent2Phone, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Parent2PhoneText = lv_textarea_create(ui_Container6);
    lv_obj_set_width(ui_Parent2PhoneText, 220);
    lv_obj_set_height(ui_Parent2PhoneText, 20);
    lv_obj_set_x(ui_Parent2PhoneText, 68);
    lv_obj_set_y(ui_Parent2PhoneText, -132);
    lv_obj_set_align(ui_Parent2PhoneText, LV_ALIGN_CENTER);

    ui_SaveButton = lv_button_create(ui_SettingsScreen);
    lv_obj_set_width(ui_SaveButton, 100);
    lv_obj_set_height(ui_SaveButton, 50);
    lv_obj_set_x(ui_SaveButton, -60);
    lv_obj_set_y(ui_SaveButton, -25);
    lv_obj_set_align(ui_SaveButton, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_SaveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SaveButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SaveButton, lv_color_hex(0x10B72D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SaveButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_SaveButton);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Save");

    ui_BackButton = lv_button_create(ui_SettingsScreen);
    lv_obj_set_width(ui_BackButton, 100);
    lv_obj_set_height(ui_BackButton, 50);
    lv_obj_set_x(ui_BackButton, 60);
    lv_obj_set_y(ui_BackButton, -25);
    lv_obj_set_align(ui_BackButton, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_BackButton);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Back");

    lv_obj_add_event_cb(ui_SaveButton, ui_event_SaveButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackButton, ui_event_BackButton, LV_EVENT_ALL, NULL);

}
