// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_CurrentSamplingRateSelections_screen_init(void)
{
    ui_CurrentSamplingRateSelections = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CurrentSamplingRateSelections, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SamplingRateTable = lv_obj_create(ui_CurrentSamplingRateSelections);
    lv_obj_remove_style_all(ui_SamplingRateTable);
    lv_obj_set_width(ui_SamplingRateTable, 280);
    lv_obj_set_height(ui_SamplingRateTable, 300);
    lv_obj_set_align(ui_SamplingRateTable, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SamplingRateTable, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_SamplingRateTable, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SamplingRateTable, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SamplingRateTableHeaderRow = lv_obj_create(ui_SamplingRateTable);
    lv_obj_remove_style_all(ui_SamplingRateTableHeaderRow);
    lv_obj_set_width(ui_SamplingRateTableHeaderRow, 280);
    lv_obj_set_height(ui_SamplingRateTableHeaderRow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SamplingRateTableHeaderRow, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_SamplingRateTableHeaderRow, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_SamplingRateTableHeaderRow, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SamplingRateTableHeaderRow, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SamplingRateTimeThLabel = lv_label_create(ui_SamplingRateTableHeaderRow);
    lv_obj_set_width(ui_SamplingRateTimeThLabel, 140);
    lv_obj_set_height(ui_SamplingRateTimeThLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SamplingRateTimeThLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SamplingRateTimeThLabel, "Time");
    lv_obj_set_style_text_align(ui_SamplingRateTimeThLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SamplingRateTimeThLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SamplingRateTimeThLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SamplingRateTimeThLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LevelThLabel = lv_label_create(ui_SamplingRateTableHeaderRow);
    lv_obj_set_width(ui_LevelThLabel, 140);
    lv_obj_set_height(ui_LevelThLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LevelThLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LevelThLabel, "Level");
    lv_obj_set_style_text_align(ui_LevelThLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LevelThLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LevelThLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LevelThLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SamplingRateTableHeaderRow1 = lv_obj_create(ui_SamplingRateTable);
    lv_obj_remove_style_all(ui_SamplingRateTableHeaderRow1);
    lv_obj_set_width(ui_SamplingRateTableHeaderRow1, 280);
    lv_obj_set_height(ui_SamplingRateTableHeaderRow1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SamplingRateTableHeaderRow1, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_SamplingRateTableHeaderRow1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_SamplingRateTableHeaderRow1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SamplingRateTableHeaderRow1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SamplingRateTimeTrLabel1 = lv_label_create(ui_SamplingRateTableHeaderRow1);
    lv_obj_set_width(ui_SamplingRateTimeTrLabel1, 140);
    lv_obj_set_height(ui_SamplingRateTimeTrLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SamplingRateTimeTrLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SamplingRateTimeTrLabel1, "00:00 to 00:00");
    lv_obj_set_style_text_align(ui_SamplingRateTimeTrLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SamplingRateTimeTrLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SamplingRateTimeTrLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SamplingRateTimeTrLabel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LevelTrLabel1 = lv_label_create(ui_SamplingRateTableHeaderRow1);
    lv_obj_set_width(ui_LevelTrLabel1, 140);
    lv_obj_set_height(ui_LevelTrLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LevelTrLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LevelTrLabel1, "medium");
    lv_obj_set_style_text_align(ui_LevelTrLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LevelTrLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LevelTrLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LevelTrLabel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SamplingRateTableTitle = lv_label_create(ui_CurrentSamplingRateSelections);
    lv_obj_set_width(ui_SamplingRateTableTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SamplingRateTableTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SamplingRateTableTitle, 0);
    lv_obj_set_y(ui_SamplingRateTableTitle, 25);
    lv_obj_set_align(ui_SamplingRateTableTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_SamplingRateTableTitle, "Sampling Rate Settings");

    ui_Button1 = lv_btn_create(ui_CurrentSamplingRateSelections);
    lv_obj_set_width(ui_Button1, 220);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 0);
    lv_obj_set_y(ui_Button1, 150);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xAD2E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Reset Sampling Rate Settings");

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CurrentSamplingRateSelections, ui_event_CurrentSamplingRateSelections, LV_EVENT_ALL, NULL);

}
