// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_MainPage_screen_init(void)
{
    ui_MainPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainPage, lv_color_hex(0xE6E6FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_MainPage);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 310);
    lv_obj_set_height(ui_Container1, 310);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FilteringOptionsButton = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_FilteringOptionsButton, 150);
    lv_obj_set_height(ui_FilteringOptionsButton, 150);
    lv_obj_set_x(ui_FilteringOptionsButton, 55);
    lv_obj_set_y(ui_FilteringOptionsButton, 47);
    lv_obj_add_flag(ui_FilteringOptionsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_FilteringOptionsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FilteringOptionsButton, 75, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FilteringOptionsButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FilteringOptionsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_FilteringOptionsButton, &ui_img_filter_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FilteringOptionsButtonLabel = lv_label_create(ui_FilteringOptionsButton);
    lv_obj_set_width(ui_FilteringOptionsButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FilteringOptionsButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FilteringOptionsButtonLabel, 0);
    lv_obj_set_y(ui_FilteringOptionsButtonLabel, 50);
    lv_obj_set_align(ui_FilteringOptionsButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FilteringOptionsButtonLabel, "Filter Options");
    lv_obj_set_style_text_color(ui_FilteringOptionsButtonLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FilteringOptionsButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PredictionsButton = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_PredictionsButton, 150);
    lv_obj_set_height(ui_PredictionsButton, 150);
    lv_obj_set_x(ui_PredictionsButton, 218);
    lv_obj_set_y(ui_PredictionsButton, 48);
    lv_obj_add_flag(ui_PredictionsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PredictionsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PredictionsButton, 75, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PredictionsButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PredictionsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_PredictionsButton, &ui_img_analytics_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PredictionButtonLabel = lv_label_create(ui_PredictionsButton);
    lv_obj_set_width(ui_PredictionButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PredictionButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PredictionButtonLabel, 0);
    lv_obj_set_y(ui_PredictionButtonLabel, 50);
    lv_obj_set_align(ui_PredictionButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PredictionButtonLabel, "Predictions");
    lv_obj_set_style_text_color(ui_PredictionButtonLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PredictionButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProfileButton = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_ProfileButton, 150);
    lv_obj_set_height(ui_ProfileButton, 150);
    lv_obj_set_x(ui_ProfileButton, 52);
    lv_obj_set_y(ui_ProfileButton, 213);
    lv_obj_add_flag(ui_ProfileButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ProfileButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ProfileButton, 75, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProfileButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProfileButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ProfileButton, &ui_img_user_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProfileButtonLabel = lv_label_create(ui_ProfileButton);
    lv_obj_set_width(ui_ProfileButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProfileButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ProfileButtonLabel, 0);
    lv_obj_set_y(ui_ProfileButtonLabel, 50);
    lv_obj_set_align(ui_ProfileButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProfileButtonLabel, "Profile");
    lv_obj_set_style_text_color(ui_ProfileButtonLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProfileButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LockButton = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_LockButton, 150);
    lv_obj_set_height(ui_LockButton, 150);
    lv_obj_set_x(ui_LockButton, 218);
    lv_obj_set_y(ui_LockButton, 210);
    lv_obj_add_flag(ui_LockButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LockButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LockButton, 75, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LockButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LockButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_LockButton, &ui_img_padlock_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LockButtonLabel = lv_label_create(ui_LockButton);
    lv_obj_set_width(ui_LockButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LockButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LockButtonLabel, 0);
    lv_obj_set_y(ui_LockButtonLabel, 50);
    lv_obj_set_align(ui_LockButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LockButtonLabel, "Lock");
    lv_obj_set_style_text_color(ui_LockButtonLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LockButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_FilteringOptionsButton, ui_event_FilteringOptionsButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PredictionsButton, ui_event_PredictionsButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ProfileButton, ui_event_ProfileButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LockButton, ui_event_LockButton, LV_EVENT_ALL, NULL);

}
