// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_SaveScreen_screen_init(void)
{
    ui_SaveScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SaveScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_SaveScreen);
    lv_obj_set_width(ui_Label13, 350);
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 0);
    lv_obj_set_y(ui_Label13, -120);
    lv_obj_set_align(ui_Label13, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label13, "Settings Saved Successfully");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_SaveScreen);
    lv_obj_set_width(ui_Panel1, 140);
    lv_obj_set_height(ui_Panel1, 140);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -50);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Panel1, &ui_img_checked_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SaveScreen, ui_event_SaveScreen, LV_EVENT_ALL, NULL);

}
