// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_LoginScreen
void ui_LoginScreen_screen_init(void);
void ui_event_LoginScreen(lv_event_t * e);
lv_obj_t * ui_LoginScreen;
lv_obj_t * ui_Image1;
lv_obj_t * ui_LoginPasswordLabel;
void ui_event_LoginPasswordTextArea(lv_event_t * e);
lv_obj_t * ui_LoginPasswordTextArea;
lv_obj_t * ui_Label2;
void ui_event_LoginButton(lv_event_t * e);
lv_obj_t * ui_LoginButton;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

// SCREEN: ui_MainPage
void ui_MainPage_screen_init(void);
lv_obj_t * ui_MainPage;
lv_obj_t * ui_Container1;
void ui_event_FilteringOptionsButton(lv_event_t * e);
lv_obj_t * ui_FilteringOptionsButton;
lv_obj_t * ui_FilteringOptionsButtonLabel;
void ui_event_PredictionsButton(lv_event_t * e);
lv_obj_t * ui_PredictionsButton;
lv_obj_t * ui_PredictionButtonLabel;
void ui_event_ProfileButton(lv_event_t * e);
lv_obj_t * ui_ProfileButton;
lv_obj_t * ui_ProfileButtonLabel;
void ui_event_LockButton(lv_event_t * e);
lv_obj_t * ui_LockButton;
lv_obj_t * ui_LockButtonLabel;
// CUSTOM VARIABLES

// SCREEN: ui_FilteringOptionsPage
void ui_FilteringOptionsPage_screen_init(void);
void ui_event_FilteringOptionsPage(lv_event_t * e);
lv_obj_t * ui_FilteringOptionsPage;
lv_obj_t * ui_FilterOptionsPageNav;
lv_obj_t * ui_FilterOptionsPage1Nav;
lv_obj_t * ui_FilterOptionsPage2Nav;
lv_obj_t * ui_FilteringPageOneBodyContainer;
lv_obj_t * ui_GenderLabel;
lv_obj_t * ui_GenderContainer;
lv_obj_t * ui_MaleCheckbox;
lv_obj_t * ui_FemaleCheckbox;
lv_obj_t * ui_EmotionLabel;
lv_obj_t * ui_EmotionContainer;
lv_obj_t * ui_AngryCheckBox;
lv_obj_t * ui_SadCheckBox;
lv_obj_t * ui_NeutralCheckBox;
lv_obj_t * ui_CalmCheckBox;
lv_obj_t * ui_HappyCheckBox;
lv_obj_t * ui_FearCheckBox;
lv_obj_t * ui_DisgustCheckBox;
lv_obj_t * ui_SurprizedCheckBox;
lv_obj_t * ui_Label16;
void ui_event_BackButtonFilterPage(lv_event_t * e);
lv_obj_t * ui_BackButtonFilterPage;
lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

// SCREEN: ui_PredictionsPage
void ui_PredictionsPage_screen_init(void);
void ui_event_PredictionsPage(lv_event_t * e);
lv_obj_t * ui_PredictionsPage;
lv_obj_t * ui_PredictionTable;
lv_obj_t * ui_PredictionTableHeaderRow;
lv_obj_t * ui_PredictionTimeThLabel2;
lv_obj_t * ui_AgeThLabel;
lv_obj_t * ui_GenderThLabel;
lv_obj_t * ui_EmotionThLabel;
lv_obj_t * ui_EmotionThLabel1;
lv_obj_t * ui_SamplingRateTableTitle2;
void ui_event_BackButtonPredictionPage(lv_event_t * e);
lv_obj_t * ui_BackButtonPredictionPage;
lv_obj_t * ui_BackButtonLabelPredictionPage;
// CUSTOM VARIABLES

// SCREEN: ui_ProfilePage
void ui_ProfilePage_screen_init(void);
void ui_event_ProfilePage(lv_event_t * e);
lv_obj_t * ui_ProfilePage;
lv_obj_t * ui_ProfileInfoTitleLabel;
lv_obj_t * ui_Container2;
lv_obj_t * ui_PrimaryPhoneNumberLabel;
void ui_event_PrimaryPhoneNumberInput(lv_event_t * e);
lv_obj_t * ui_PrimaryPhoneNumberInput;
lv_obj_t * ui_SecondaryPhoneNumberLabel;
void ui_event_SecondaryPhoneNumberInput(lv_event_t * e);
lv_obj_t * ui_SecondaryPhoneNumberInput;
lv_obj_t * ui_ProfilePagePasswordLabel;
void ui_event_ProfilePagePasswordInput(lv_event_t * e);
lv_obj_t * ui_ProfilePagePasswordInput;
void ui_event_ProfilePageSaveButton(lv_event_t * e);
lv_obj_t * ui_ProfilePageSaveButton;
lv_obj_t * ui_ProfilePageSaveButtonLabel;
lv_obj_t * ui_ProfilePageKeyboard;
lv_obj_t * ui_ProfilePageKeyboard1;
lv_obj_t * ui_ProfilePageKeyboard2;
// CUSTOM VARIABLES

// SCREEN: ui_LockPage
void ui_LockPage_screen_init(void);
void ui_event_LockPage(lv_event_t * e);
lv_obj_t * ui_LockPage;
lv_obj_t * ui_LockPageTimeLabel;
// CUSTOM VARIABLES

// SCREEN: ui_SaveScreen
void ui_SaveScreen_screen_init(void);
void ui_event_SaveScreen(lv_event_t * e);
lv_obj_t * ui_SaveScreen;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Panel1;
// CUSTOM VARIABLES

// SCREEN: ui_FilteringOptionsPage2
void ui_FilteringOptionsPage2_screen_init(void);
void ui_event_FilteringOptionsPage2(lv_event_t * e);
lv_obj_t * ui_FilteringOptionsPage2;
lv_obj_t * ui_FilterOptionsPageNav1;
lv_obj_t * ui_FilterOptionsPage1Nav1;
lv_obj_t * ui_FilterOptionsPage2Nav1;
lv_obj_t * ui_FilteringPageOneBodyContainer1;
lv_obj_t * ui_AgeLabel;
lv_obj_t * ui_AgeContainer;
lv_obj_t * ui_twentyCheckbox;
lv_obj_t * ui_thirtyCheckbox;
lv_obj_t * ui_fortyCheckbox;
lv_obj_t * ui_fiftyCheckbox;
lv_obj_t * ui_sixtyCheckbox;
lv_obj_t * ui_seventyCheckbox;
lv_obj_t * ui_eightyCheckbox;
lv_obj_t * ui_Label19;
lv_obj_t * ui_SamplingRateContainerLabel;
lv_obj_t * ui_LowCheckbox;
lv_obj_t * ui_MediumCheckbox;
lv_obj_t * ui_HighCheckbox1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Dropdown1;
lv_obj_t * ui_Dropdown2;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
// CUSTOM VARIABLES

// SCREEN: ui_CurrentSamplingRateSelections
void ui_CurrentSamplingRateSelections_screen_init(void);
void ui_event_CurrentSamplingRateSelections(lv_event_t * e);
lv_obj_t * ui_CurrentSamplingRateSelections;
lv_obj_t * ui_SamplingRateTable;
lv_obj_t * ui_SamplingRateTableHeaderRow;
lv_obj_t * ui_SamplingRateTimeThLabel;
lv_obj_t * ui_LevelThLabel;
lv_obj_t * ui_SamplingRateTableHeaderRow1;
lv_obj_t * ui_SamplingRateTimeTrLabel1;
lv_obj_t * ui_LevelTrLabel1;
lv_obj_t * ui_SamplingRateTableTitle;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

// SCREEN: ui_SaveSamplingRateNotification
void ui_SaveSamplingRateNotification_screen_init(void);
void ui_event_SaveSamplingRateNotification(lv_event_t * e);
lv_obj_t * ui_SaveSamplingRateNotification;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Panel2;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_LoginScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_LoginPasswordTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_LoginButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CheckPassword(e);
    }
}

void ui_event_FilteringOptionsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_FilteringOptionsPage, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_FilteringOptionsPage_screen_init);
    }
}

void ui_event_PredictionsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PredictionsPage, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_PredictionsPage_screen_init);
    }
}

void ui_event_ProfileButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ProfilePage, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ProfilePage_screen_init);
    }
}

void ui_event_LockButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_LockPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_LockPage_screen_init);
    }
}

void ui_event_FilteringOptionsPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_FilteringOptionsPage2, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_FilteringOptionsPage2_screen_init);
    }
}

void ui_event_BackButtonFilterPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainPage, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_MainPage_screen_init);
    }
}

void ui_event_PredictionsPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        LoadPredictionTableValues(e);
    }
}

void ui_event_BackButtonPredictionPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainPage, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_MainPage_screen_init);
    }
}

void ui_event_ProfilePage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        LoadProfileInformation(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ProfilePageKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ProfilePageKeyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ProfilePageKeyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_PrimaryPhoneNumberInput(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ProfilePageKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_SecondaryPhoneNumberInput(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ProfilePageKeyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_ProfilePagePasswordInput(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ProfilePageKeyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_ProfilePageSaveButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SaveProfileInformationCallback(e);
        _ui_screen_change(&ui_SaveScreen, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_SaveScreen_screen_init);
    }
}

void ui_event_LockPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_LoginScreen, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_LoginScreen_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        UpdateLockScreenTime(e);
    }
}

void ui_event_SaveScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_MainPage, LV_SCR_LOAD_ANIM_FADE_ON, 300, 1000, &ui_MainPage_screen_init);
    }
}

void ui_event_FilteringOptionsPage2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_FilteringOptionsPage, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_FilteringOptionsPage_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_CurrentSamplingRateSelections, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0,
                          &ui_CurrentSamplingRateSelections_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SaveSamplingRateNotification, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0,
                          &ui_SaveSamplingRateNotification_screen_init);
        SaveSamplingRateToFile(e);
    }
}

void ui_event_CurrentSamplingRateSelections(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_FilteringOptionsPage2, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_FilteringOptionsPage2_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        LoadSamplingRateValues(e);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ClearSamplingRateTable(e);
    }
}

void ui_event_SaveSamplingRateNotification(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_FilteringOptionsPage2, LV_SCR_LOAD_ANIM_FADE_ON, 300, 1000,
                          &ui_FilteringOptionsPage2_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_LoginScreen_screen_init();
    ui_MainPage_screen_init();
    ui_FilteringOptionsPage_screen_init();
    ui_PredictionsPage_screen_init();
    ui_ProfilePage_screen_init();
    ui_LockPage_screen_init();
    ui_SaveScreen_screen_init();
    ui_FilteringOptionsPage2_screen_init();
    ui_CurrentSamplingRateSelections_screen_init();
    ui_SaveSamplingRateNotification_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_LockPage);
}
