// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_LoginScreen
void ui_LoginScreen_screen_init(void);
void ui_event_LoginScreen(lv_event_t * e);
extern lv_obj_t * ui_LoginScreen;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_LoginPasswordLabel;
void ui_event_LoginPasswordTextArea(lv_event_t * e);
extern lv_obj_t * ui_LoginPasswordTextArea;
extern lv_obj_t * ui_Label2;
void ui_event_LoginButton(lv_event_t * e);
extern lv_obj_t * ui_LoginButton;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

// SCREEN: ui_MainPage
void ui_MainPage_screen_init(void);
extern lv_obj_t * ui_MainPage;
extern lv_obj_t * ui_Container1;
void ui_event_FilteringOptionsButton(lv_event_t * e);
extern lv_obj_t * ui_FilteringOptionsButton;
extern lv_obj_t * ui_FilteringOptionsButtonLabel;
void ui_event_PredictionsButton(lv_event_t * e);
extern lv_obj_t * ui_PredictionsButton;
extern lv_obj_t * ui_PredictionButtonLabel;
void ui_event_ProfileButton(lv_event_t * e);
extern lv_obj_t * ui_ProfileButton;
extern lv_obj_t * ui_ProfileButtonLabel;
void ui_event_LockButton(lv_event_t * e);
extern lv_obj_t * ui_LockButton;
extern lv_obj_t * ui_LockButtonLabel;
// CUSTOM VARIABLES

// SCREEN: ui_FilteringOptionsPage
void ui_FilteringOptionsPage_screen_init(void);
void ui_event_FilteringOptionsPage(lv_event_t * e);
extern lv_obj_t * ui_FilteringOptionsPage;
extern lv_obj_t * ui_FilterOptionsPageNav;
extern lv_obj_t * ui_FilterOptionsPage1Nav;
extern lv_obj_t * ui_FilterOptionsPage2Nav;
extern lv_obj_t * ui_FilteringPageOneBodyContainer;
extern lv_obj_t * ui_GenderLabel;
extern lv_obj_t * ui_GenderContainer;
extern lv_obj_t * ui_MaleCheckbox;
extern lv_obj_t * ui_FemaleCheckbox;
extern lv_obj_t * ui_EmotionLabel;
extern lv_obj_t * ui_EmotionContainer;
extern lv_obj_t * ui_AngryCheckBox;
extern lv_obj_t * ui_SadCheckBox;
extern lv_obj_t * ui_NeutralCheckBox;
extern lv_obj_t * ui_CalmCheckBox;
extern lv_obj_t * ui_HappyCheckBox;
extern lv_obj_t * ui_FearCheckBox;
extern lv_obj_t * ui_DisgustCheckBox;
extern lv_obj_t * ui_SurprizedCheckBox;
extern lv_obj_t * ui_Label16;
void ui_event_BackButtonFilterPage(lv_event_t * e);
extern lv_obj_t * ui_BackButtonFilterPage;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

// SCREEN: ui_PredictionsPage
void ui_PredictionsPage_screen_init(void);
void ui_event_PredictionsPage(lv_event_t * e);
extern lv_obj_t * ui_PredictionsPage;
extern lv_obj_t * ui_PredictionTable;
extern lv_obj_t * ui_PredictionTableHeaderRow;
extern lv_obj_t * ui_PredictionTimeThLabel2;
extern lv_obj_t * ui_AgeThLabel;
extern lv_obj_t * ui_GenderThLabel;
extern lv_obj_t * ui_EmotionThLabel;
extern lv_obj_t * ui_EmotionThLabel1;
extern lv_obj_t * ui_SamplingRateTableTitle2;
void ui_event_BackButtonPredictionPage(lv_event_t * e);
extern lv_obj_t * ui_BackButtonPredictionPage;
extern lv_obj_t * ui_BackButtonLabelPredictionPage;
// CUSTOM VARIABLES

// SCREEN: ui_ProfilePage
void ui_ProfilePage_screen_init(void);
void ui_event_ProfilePage(lv_event_t * e);
extern lv_obj_t * ui_ProfilePage;
extern lv_obj_t * ui_ProfileInfoTitleLabel;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_PrimaryPhoneNumberLabel;
void ui_event_PrimaryPhoneNumberInput(lv_event_t * e);
extern lv_obj_t * ui_PrimaryPhoneNumberInput;
extern lv_obj_t * ui_SecondaryPhoneNumberLabel;
void ui_event_SecondaryPhoneNumberInput(lv_event_t * e);
extern lv_obj_t * ui_SecondaryPhoneNumberInput;
extern lv_obj_t * ui_ProfilePagePasswordLabel;
void ui_event_ProfilePagePasswordInput(lv_event_t * e);
extern lv_obj_t * ui_ProfilePagePasswordInput;
void ui_event_ProfilePageSaveButton(lv_event_t * e);
extern lv_obj_t * ui_ProfilePageSaveButton;
extern lv_obj_t * ui_ProfilePageSaveButtonLabel;
extern lv_obj_t * ui_ProfilePageKeyboard;
extern lv_obj_t * ui_ProfilePageKeyboard1;
extern lv_obj_t * ui_ProfilePageKeyboard2;
// CUSTOM VARIABLES

// SCREEN: ui_LockPage
void ui_LockPage_screen_init(void);
void ui_event_LockPage(lv_event_t * e);
extern lv_obj_t * ui_LockPage;
extern lv_obj_t * ui_LockPageTimeLabel;
// CUSTOM VARIABLES

// SCREEN: ui_SaveScreen
void ui_SaveScreen_screen_init(void);
void ui_event_SaveScreen(lv_event_t * e);
extern lv_obj_t * ui_SaveScreen;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel1;
// CUSTOM VARIABLES

// SCREEN: ui_FilteringOptionsPage2
void ui_FilteringOptionsPage2_screen_init(void);
void ui_event_FilteringOptionsPage2(lv_event_t * e);
extern lv_obj_t * ui_FilteringOptionsPage2;
extern lv_obj_t * ui_FilterOptionsPageNav1;
extern lv_obj_t * ui_FilterOptionsPage1Nav1;
extern lv_obj_t * ui_FilterOptionsPage2Nav1;
extern lv_obj_t * ui_FilteringPageOneBodyContainer1;
extern lv_obj_t * ui_AgeLabel;
extern lv_obj_t * ui_AgeContainer;
extern lv_obj_t * ui_twentyCheckbox;
extern lv_obj_t * ui_thirtyCheckbox;
extern lv_obj_t * ui_fortyCheckbox;
extern lv_obj_t * ui_fiftyCheckbox;
extern lv_obj_t * ui_sixtyCheckbox;
extern lv_obj_t * ui_seventyCheckbox;
extern lv_obj_t * ui_eightyCheckbox;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_SamplingRateContainerLabel;
extern lv_obj_t * ui_LowCheckbox;
extern lv_obj_t * ui_MediumCheckbox;
extern lv_obj_t * ui_HighCheckbox1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Dropdown2;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
// CUSTOM VARIABLES

// SCREEN: ui_CurrentSamplingRateSelections
void ui_CurrentSamplingRateSelections_screen_init(void);
void ui_event_CurrentSamplingRateSelections(lv_event_t * e);
extern lv_obj_t * ui_CurrentSamplingRateSelections;
extern lv_obj_t * ui_SamplingRateTable;
extern lv_obj_t * ui_SamplingRateTableHeaderRow;
extern lv_obj_t * ui_SamplingRateTimeThLabel;
extern lv_obj_t * ui_LevelThLabel;
extern lv_obj_t * ui_SamplingRateTableHeaderRow1;
extern lv_obj_t * ui_SamplingRateTimeTrLabel1;
extern lv_obj_t * ui_LevelTrLabel1;
extern lv_obj_t * ui_SamplingRateTableTitle;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

// SCREEN: ui_SaveSamplingRateNotification
void ui_SaveSamplingRateNotification_screen_init(void);
void ui_event_SaveSamplingRateNotification(lv_event_t * e);
extern lv_obj_t * ui_SaveSamplingRateNotification;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel2;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_padlock_png);    // assets/padlock.png
LV_IMG_DECLARE(ui_img_filter_png);    // assets/filter.png
LV_IMG_DECLARE(ui_img_analytics_png);    // assets/analytics.png
LV_IMG_DECLARE(ui_img_user_png);    // assets/user.png
LV_IMG_DECLARE(ui_img_checked_png);    // assets/checked.png
LV_IMG_DECLARE(ui_img_plus_png);    // assets/plus.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
