// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void CheckPassword(lv_event_t * e);
void LoadPredictionTableValues(lv_event_t * e);
void LoadProfileInformation(lv_event_t * e);
void SaveProfileInformationCallback(lv_event_t * e);
void UpdateLockScreenTime(lv_event_t * e);
void SaveSamplingRateToFile(lv_event_t * e);
void LoadSamplingRateValues(lv_event_t * e);
void ClearSamplingRateTable(lv_event_t * e);
void SaveProfileInformation();
void SaveFilteringConfig();

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
