// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_FilteringOptionsPage2_screen_init(void)
{
    ui_FilteringOptionsPage2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FilteringOptionsPage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FilteringOptionsPage2, lv_color_hex(0xE6E6FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FilteringOptionsPage2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FilterOptionsPageNav1 = lv_obj_create(ui_FilteringOptionsPage2);
    lv_obj_remove_style_all(ui_FilterOptionsPageNav1);
    lv_obj_set_width(ui_FilterOptionsPageNav1, 100);
    lv_obj_set_height(ui_FilterOptionsPageNav1, 50);
    lv_obj_set_x(ui_FilterOptionsPageNav1, 0);
    lv_obj_set_y(ui_FilterOptionsPageNav1, -30);
    lv_obj_set_align(ui_FilterOptionsPageNav1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_FilterOptionsPageNav1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FilterOptionsPage1Nav1 = lv_obj_create(ui_FilterOptionsPageNav1);
    lv_obj_remove_style_all(ui_FilterOptionsPage1Nav1);
    lv_obj_set_width(ui_FilterOptionsPage1Nav1, 20);
    lv_obj_set_height(ui_FilterOptionsPage1Nav1, 20);
    lv_obj_set_align(ui_FilterOptionsPage1Nav1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_FilterOptionsPage1Nav1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FilterOptionsPage1Nav1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FilterOptionsPage1Nav1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FilterOptionsPage1Nav1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FilterOptionsPage2Nav1 = lv_obj_create(ui_FilterOptionsPageNav1);
    lv_obj_remove_style_all(ui_FilterOptionsPage2Nav1);
    lv_obj_set_width(ui_FilterOptionsPage2Nav1, 20);
    lv_obj_set_height(ui_FilterOptionsPage2Nav1, 20);
    lv_obj_set_align(ui_FilterOptionsPage2Nav1, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_FilterOptionsPage2Nav1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FilterOptionsPage2Nav1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FilterOptionsPage2Nav1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FilterOptionsPage2Nav1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FilteringPageOneBodyContainer1 = lv_obj_create(ui_FilteringOptionsPage2);
    lv_obj_remove_style_all(ui_FilteringPageOneBodyContainer1);
    lv_obj_set_width(ui_FilteringPageOneBodyContainer1, 400);
    lv_obj_set_height(ui_FilteringPageOneBodyContainer1, 261);
    lv_obj_set_align(ui_FilteringPageOneBodyContainer1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_FilteringPageOneBodyContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AgeLabel = lv_label_create(ui_FilteringPageOneBodyContainer1);
    lv_obj_set_width(ui_AgeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AgeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AgeLabel, 60);
    lv_obj_set_y(ui_AgeLabel, 0);
    lv_label_set_text(ui_AgeLabel, "Age:");

    ui_AgeContainer = lv_obj_create(ui_FilteringPageOneBodyContainer1);
    lv_obj_remove_style_all(ui_AgeContainer);
    lv_obj_set_width(ui_AgeContainer, 380);
    lv_obj_set_height(ui_AgeContainer, 110);
    lv_obj_set_x(ui_AgeContainer, 10);
    lv_obj_set_y(ui_AgeContainer, 30);
    lv_obj_set_flex_flow(ui_AgeContainer, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_AgeContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_AgeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_AgeContainer, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AgeContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AgeContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AgeContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_AgeContainer, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_AgeContainer, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_twentyCheckbox = lv_checkbox_create(ui_AgeContainer);
    lv_checkbox_set_text(ui_twentyCheckbox, "20s");
    lv_obj_set_width(ui_twentyCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_twentyCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_twentyCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_twentyCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_thirtyCheckbox = lv_checkbox_create(ui_AgeContainer);
    lv_checkbox_set_text(ui_thirtyCheckbox, "30s");
    lv_obj_set_width(ui_thirtyCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_thirtyCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_thirtyCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_thirtyCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_fortyCheckbox = lv_checkbox_create(ui_AgeContainer);
    lv_checkbox_set_text(ui_fortyCheckbox, "40s");
    lv_obj_set_width(ui_fortyCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fortyCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_fortyCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fortyCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_fiftyCheckbox = lv_checkbox_create(ui_AgeContainer);
    lv_checkbox_set_text(ui_fiftyCheckbox, "50s");
    lv_obj_set_width(ui_fiftyCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fiftyCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_fiftyCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fiftyCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_sixtyCheckbox = lv_checkbox_create(ui_AgeContainer);
    lv_checkbox_set_text(ui_sixtyCheckbox, "60s");
    lv_obj_set_width(ui_sixtyCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sixtyCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_sixtyCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sixtyCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_seventyCheckbox = lv_checkbox_create(ui_AgeContainer);
    lv_checkbox_set_text(ui_seventyCheckbox, "70s");
    lv_obj_set_width(ui_seventyCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_seventyCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_seventyCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seventyCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_eightyCheckbox = lv_checkbox_create(ui_AgeContainer);
    lv_checkbox_set_text(ui_eightyCheckbox, "80s");
    lv_obj_set_width(ui_eightyCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_eightyCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_eightyCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_eightyCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label19 = lv_label_create(ui_FilteringPageOneBodyContainer1);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 0);
    lv_obj_set_y(ui_Label19, -72);
    lv_obj_set_align(ui_Label19, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label19, "to");

    ui_SamplingRateContainerLabel = lv_label_create(ui_FilteringPageOneBodyContainer1);
    lv_obj_set_width(ui_SamplingRateContainerLabel, 300);
    lv_obj_set_height(ui_SamplingRateContainerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SamplingRateContainerLabel, 10);
    lv_obj_set_y(ui_SamplingRateContainerLabel, -107);
    lv_obj_set_align(ui_SamplingRateContainerLabel, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_SamplingRateContainerLabel, "Sampling Rate:");

    ui_LowCheckbox = lv_checkbox_create(ui_FilteringPageOneBodyContainer1);
    lv_checkbox_set_text(ui_LowCheckbox, "Low");
    lv_obj_set_width(ui_LowCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowCheckbox, 120);
    lv_obj_set_y(ui_LowCheckbox, -35);
    lv_obj_set_align(ui_LowCheckbox, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_LowCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_MediumCheckbox = lv_checkbox_create(ui_FilteringPageOneBodyContainer1);
    lv_checkbox_set_text(ui_MediumCheckbox, "Medium");
    lv_obj_set_width(ui_MediumCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MediumCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MediumCheckbox, 0);
    lv_obj_set_y(ui_MediumCheckbox, -35);
    lv_obj_set_align(ui_MediumCheckbox, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_MediumCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_HighCheckbox1 = lv_checkbox_create(ui_FilteringPageOneBodyContainer1);
    lv_checkbox_set_text(ui_HighCheckbox1, "High");
    lv_obj_set_width(ui_HighCheckbox1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HighCheckbox1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HighCheckbox1, -120);
    lv_obj_set_y(ui_HighCheckbox1, -35);
    lv_obj_set_align(ui_HighCheckbox1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_HighCheckbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label1 = lv_label_create(ui_FilteringOptionsPage2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, 40);
    lv_obj_set_align(ui_Label1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label1, "Filtering Options");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_FilteringOptionsPage2);
    lv_dropdown_set_dir(ui_Dropdown1, LV_DIR_RIGHT);
    lv_dropdown_set_options(ui_Dropdown1,
                            "00:00\n01:00\n02:00\n03:00\n04:00\n05:00\n06:00\n07:00\n08:00\n09:00\n10:00\n11:00\n12:00\n13:00\n14:00\n15:00\n16:00\n17:00\n18:00\n19:00\n20:00\n21:00\n22:00\n23:00");
    lv_obj_set_width(ui_Dropdown1, 150);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, -100);
    lv_obj_set_y(ui_Dropdown1, -140);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Dropdown2 = lv_dropdown_create(ui_FilteringOptionsPage2);
    lv_dropdown_set_dir(ui_Dropdown2, LV_DIR_LEFT);
    lv_dropdown_set_options(ui_Dropdown2,
                            "00:00\n01:00\n02:00\n03:00\n04:00\n05:00\n06:00\n07:00\n08:00\n09:00\n10:00\n11:00\n12:00\n13:00\n14:00\n15:00\n16:00\n17:00\n18:00\n19:00\n20:00\n21:00\n22:00\n23:00");
    lv_obj_set_width(ui_Dropdown2, 150);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, 100);
    lv_obj_set_y(ui_Dropdown2, -140);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Button4 = lv_btn_create(ui_FilteringOptionsPage2);
    lv_obj_set_width(ui_Button4, 30);
    lv_obj_set_height(ui_Button4, 30);
    lv_obj_set_x(ui_Button4, 0);
    lv_obj_set_y(ui_Button4, -70);
    lv_obj_set_align(ui_Button4, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button4, &ui_img_plus_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FilteringOptionsPage2, ui_event_FilteringOptionsPage2, LV_EVENT_ALL, NULL);

}
