// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_FilteringOptionsPage_screen_init(void)
{
    ui_FilteringOptionsPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FilteringOptionsPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FilteringOptionsPage, lv_color_hex(0xE6E6FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FilteringOptionsPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FilterOptionsPageNav = lv_obj_create(ui_FilteringOptionsPage);
    lv_obj_remove_style_all(ui_FilterOptionsPageNav);
    lv_obj_set_width(ui_FilterOptionsPageNav, 100);
    lv_obj_set_height(ui_FilterOptionsPageNav, 50);
    lv_obj_set_x(ui_FilterOptionsPageNav, 0);
    lv_obj_set_y(ui_FilterOptionsPageNav, -30);
    lv_obj_set_align(ui_FilterOptionsPageNav, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_FilterOptionsPageNav, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FilterOptionsPage1Nav = lv_obj_create(ui_FilterOptionsPageNav);
    lv_obj_remove_style_all(ui_FilterOptionsPage1Nav);
    lv_obj_set_width(ui_FilterOptionsPage1Nav, 20);
    lv_obj_set_height(ui_FilterOptionsPage1Nav, 20);
    lv_obj_set_align(ui_FilterOptionsPage1Nav, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_FilterOptionsPage1Nav, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FilterOptionsPage1Nav, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FilterOptionsPage1Nav, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FilterOptionsPage1Nav, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FilterOptionsPage2Nav = lv_obj_create(ui_FilterOptionsPageNav);
    lv_obj_remove_style_all(ui_FilterOptionsPage2Nav);
    lv_obj_set_width(ui_FilterOptionsPage2Nav, 20);
    lv_obj_set_height(ui_FilterOptionsPage2Nav, 20);
    lv_obj_set_align(ui_FilterOptionsPage2Nav, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_FilterOptionsPage2Nav, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FilterOptionsPage2Nav, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FilterOptionsPage2Nav, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FilterOptionsPage2Nav, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FilteringPageOneBodyContainer = lv_obj_create(ui_FilteringOptionsPage);
    lv_obj_remove_style_all(ui_FilteringPageOneBodyContainer);
    lv_obj_set_width(ui_FilteringPageOneBodyContainer, 400);
    lv_obj_set_height(ui_FilteringPageOneBodyContainer, 261);
    lv_obj_set_align(ui_FilteringPageOneBodyContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_FilteringPageOneBodyContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GenderLabel = lv_label_create(ui_FilteringPageOneBodyContainer);
    lv_obj_set_width(ui_GenderLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GenderLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GenderLabel, 60);
    lv_obj_set_y(ui_GenderLabel, 0);
    lv_label_set_text(ui_GenderLabel, "Gender:");

    ui_GenderContainer = lv_obj_create(ui_FilteringPageOneBodyContainer);
    lv_obj_remove_style_all(ui_GenderContainer);
    lv_obj_set_width(ui_GenderContainer, 310);
    lv_obj_set_height(ui_GenderContainer, 20);
    lv_obj_set_x(ui_GenderContainer, 70);
    lv_obj_set_y(ui_GenderContainer, 20);
    lv_obj_set_flex_flow(ui_GenderContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_GenderContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_GenderContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_GenderContainer, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_GenderContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_GenderContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_GenderContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_GenderContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_GenderContainer, 70, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MaleCheckbox = lv_checkbox_create(ui_GenderContainer);
    lv_checkbox_set_text(ui_MaleCheckbox, "Male");
    lv_obj_set_width(ui_MaleCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MaleCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MaleCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MaleCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_FemaleCheckbox = lv_checkbox_create(ui_GenderContainer);
    lv_checkbox_set_text(ui_FemaleCheckbox, "Female");
    lv_obj_set_width(ui_FemaleCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FemaleCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FemaleCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FemaleCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_EmotionLabel = lv_label_create(ui_FilteringPageOneBodyContainer);
    lv_obj_set_width(ui_EmotionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EmotionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EmotionLabel, 60);
    lv_obj_set_y(ui_EmotionLabel, 70);
    lv_label_set_text(ui_EmotionLabel, "Emotions:");

    ui_EmotionContainer = lv_obj_create(ui_FilteringPageOneBodyContainer);
    lv_obj_remove_style_all(ui_EmotionContainer);
    lv_obj_set_width(ui_EmotionContainer, 380);
    lv_obj_set_height(ui_EmotionContainer, 110);
    lv_obj_set_x(ui_EmotionContainer, 10);
    lv_obj_set_y(ui_EmotionContainer, 90);
    lv_obj_set_flex_flow(ui_EmotionContainer, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_EmotionContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_EmotionContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_EmotionContainer, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_EmotionContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_EmotionContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_EmotionContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_EmotionContainer, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_EmotionContainer, 70, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AngryCheckBox = lv_checkbox_create(ui_EmotionContainer);
    lv_checkbox_set_text(ui_AngryCheckBox, "Angry");
    lv_obj_set_width(ui_AngryCheckBox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AngryCheckBox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AngryCheckBox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AngryCheckBox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_SadCheckBox = lv_checkbox_create(ui_EmotionContainer);
    lv_checkbox_set_text(ui_SadCheckBox, "Sad");
    lv_obj_set_width(ui_SadCheckBox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SadCheckBox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SadCheckBox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SadCheckBox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_NeutralCheckBox = lv_checkbox_create(ui_EmotionContainer);
    lv_checkbox_set_text(ui_NeutralCheckBox, "Netural");
    lv_obj_set_width(ui_NeutralCheckBox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NeutralCheckBox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NeutralCheckBox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NeutralCheckBox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_CalmCheckBox = lv_checkbox_create(ui_EmotionContainer);
    lv_checkbox_set_text(ui_CalmCheckBox, "Calm");
    lv_obj_set_width(ui_CalmCheckBox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalmCheckBox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CalmCheckBox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalmCheckBox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_HappyCheckBox = lv_checkbox_create(ui_EmotionContainer);
    lv_checkbox_set_text(ui_HappyCheckBox, "Happy");
    lv_obj_set_width(ui_HappyCheckBox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HappyCheckBox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HappyCheckBox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HappyCheckBox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_FearCheckBox = lv_checkbox_create(ui_EmotionContainer);
    lv_checkbox_set_text(ui_FearCheckBox, "Fear");
    lv_obj_set_width(ui_FearCheckBox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FearCheckBox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FearCheckBox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FearCheckBox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_DisgustCheckBox = lv_checkbox_create(ui_EmotionContainer);
    lv_checkbox_set_text(ui_DisgustCheckBox, "Disgust");
    lv_obj_set_width(ui_DisgustCheckBox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DisgustCheckBox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DisgustCheckBox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DisgustCheckBox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_SurprizedCheckBox = lv_checkbox_create(ui_EmotionContainer);
    lv_checkbox_set_text(ui_SurprizedCheckBox, "Surprized");
    lv_obj_set_width(ui_SurprizedCheckBox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SurprizedCheckBox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SurprizedCheckBox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SurprizedCheckBox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label16 = lv_label_create(ui_FilteringOptionsPage);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 0);
    lv_obj_set_y(ui_Label16, 40);
    lv_obj_set_align(ui_Label16, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label16, "Filtering Options");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButtonFilterPage = lv_btn_create(ui_FilteringOptionsPage);
    lv_obj_set_width(ui_BackButtonFilterPage, 70);
    lv_obj_set_height(ui_BackButtonFilterPage, 30);
    lv_obj_set_x(ui_BackButtonFilterPage, 0);
    lv_obj_set_y(ui_BackButtonFilterPage, 100);
    lv_obj_set_align(ui_BackButtonFilterPage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackButtonFilterPage, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackButtonFilterPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_BackButtonFilterPage);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Back");

    lv_obj_add_event_cb(ui_BackButtonFilterPage, ui_event_BackButtonFilterPage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FilteringOptionsPage, ui_event_FilteringOptionsPage, LV_EVENT_ALL, NULL);

}
