// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_LoginScreen_screen_init(void)
{
    ui_LoginScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LoginScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LoginScreen, lv_color_hex(0xE6E6FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoginScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_LoginScreen);
    lv_img_set_src(ui_Image1, &ui_img_padlock_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -140);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LoginPasswordLabel = lv_label_create(ui_LoginScreen);
    lv_obj_set_width(ui_LoginPasswordLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LoginPasswordLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LoginPasswordLabel, 50);
    lv_obj_set_y(ui_LoginPasswordLabel, -40);
    lv_obj_set_align(ui_LoginPasswordLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LoginPasswordLabel, "Password");
    lv_obj_set_style_text_font(ui_LoginPasswordLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoginPasswordTextArea = lv_textarea_create(ui_LoginScreen);
    lv_obj_set_width(ui_LoginPasswordTextArea, 250);
    lv_obj_set_height(ui_LoginPasswordTextArea, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LoginPasswordTextArea, 50);
    lv_obj_set_y(ui_LoginPasswordTextArea, 0);
    lv_obj_set_align(ui_LoginPasswordTextArea, LV_ALIGN_LEFT_MID);
    if("abcdefghijklmnopqrstuvwxyz0123456789!+%?-_*" == "") lv_textarea_set_accepted_chars(ui_LoginPasswordTextArea, NULL);
    else lv_textarea_set_accepted_chars(ui_LoginPasswordTextArea, "abcdefghijklmnopqrstuvwxyz0123456789!+%?-_*");
    lv_textarea_set_max_length(ui_LoginPasswordTextArea, 12);
    lv_textarea_set_placeholder_text(ui_LoginPasswordTextArea, "Enter Password");
    lv_textarea_set_one_line(ui_LoginPasswordTextArea, true);
    lv_textarea_set_password_mode(ui_LoginPasswordTextArea, true);

    ui_Label2 = lv_label_create(ui_LoginScreen);
    lv_obj_set_width(ui_Label2, 250);
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, -80);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Please enter application password");

    ui_LoginButton = lv_btn_create(ui_LoginScreen);
    lv_obj_set_width(ui_LoginButton, 100);
    lv_obj_set_height(ui_LoginButton, 50);
    lv_obj_set_x(ui_LoginButton, 0);
    lv_obj_set_y(ui_LoginButton, 100);
    lv_obj_set_align(ui_LoginButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LoginButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LoginButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LoginButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoginButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_LoginButton);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Login");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x010101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_LoginScreen);
    lv_obj_set_width(ui_Keyboard1, 300);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 90);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_LoginPasswordTextArea, ui_event_LoginPasswordTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LoginButton, ui_event_LoginButton, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_LoginPasswordTextArea);
    lv_obj_add_event_cb(ui_LoginScreen, ui_event_LoginScreen, LV_EVENT_ALL, NULL);

}
