// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_LockPage_screen_init(void)
{
    ui_LockPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LockPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LockPage, lv_color_hex(0xE6E6FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LockPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LockPageTimeLabel = lv_label_create(ui_LockPage);
    lv_obj_set_width(ui_LockPageTimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LockPageTimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LockPageTimeLabel, 0);
    lv_obj_set_y(ui_LockPageTimeLabel, -70);
    lv_obj_set_align(ui_LockPageTimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LockPageTimeLabel, "15:24");
    lv_obj_set_style_text_font(ui_LockPageTimeLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_LockPage, ui_event_LockPage, LV_EVENT_ALL, NULL);

}
