// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_ProfilePage_screen_init(void)
{
    ui_ProfilePage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ProfilePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ProfilePage, lv_color_hex(0xE6E6FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProfilePage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProfileInfoTitleLabel = lv_label_create(ui_ProfilePage);
    lv_obj_set_width(ui_ProfileInfoTitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProfileInfoTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ProfileInfoTitleLabel, 0);
    lv_obj_set_y(ui_ProfileInfoTitleLabel, -140);
    lv_obj_set_align(ui_ProfileInfoTitleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProfileInfoTitleLabel, "Profile Information");
    lv_obj_set_style_text_font(ui_ProfileInfoTitleLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_ProfilePage);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 309);
    lv_obj_set_height(ui_Container2, 229);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 10);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrimaryPhoneNumberLabel = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_PrimaryPhoneNumberLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrimaryPhoneNumberLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PrimaryPhoneNumberLabel, 10);
    lv_obj_set_y(ui_PrimaryPhoneNumberLabel, 0);
    lv_label_set_text(ui_PrimaryPhoneNumberLabel, "Primary phone number");

    ui_PrimaryPhoneNumberInput = lv_textarea_create(ui_Container2);
    lv_obj_set_width(ui_PrimaryPhoneNumberInput, 200);
    lv_obj_set_height(ui_PrimaryPhoneNumberInput, 40);
    lv_obj_set_x(ui_PrimaryPhoneNumberInput, 10);
    lv_obj_set_y(ui_PrimaryPhoneNumberInput, 20);
    if("0123456789+" == "") lv_textarea_set_accepted_chars(ui_PrimaryPhoneNumberInput, NULL);
    else lv_textarea_set_accepted_chars(ui_PrimaryPhoneNumberInput, "0123456789+");
    lv_textarea_set_max_length(ui_PrimaryPhoneNumberInput, 10);
    lv_textarea_set_placeholder_text(ui_PrimaryPhoneNumberInput, "+90");

    ui_SecondaryPhoneNumberLabel = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_SecondaryPhoneNumberLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SecondaryPhoneNumberLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SecondaryPhoneNumberLabel, 10);
    lv_obj_set_y(ui_SecondaryPhoneNumberLabel, 70);
    lv_label_set_text(ui_SecondaryPhoneNumberLabel, "Secondary phone number");

    ui_SecondaryPhoneNumberInput = lv_textarea_create(ui_Container2);
    lv_obj_set_width(ui_SecondaryPhoneNumberInput, 200);
    lv_obj_set_height(ui_SecondaryPhoneNumberInput, 40);
    lv_obj_set_x(ui_SecondaryPhoneNumberInput, 10);
    lv_obj_set_y(ui_SecondaryPhoneNumberInput, 90);
    if("0123456789+" == "") lv_textarea_set_accepted_chars(ui_SecondaryPhoneNumberInput, NULL);
    else lv_textarea_set_accepted_chars(ui_SecondaryPhoneNumberInput, "0123456789+");
    lv_textarea_set_max_length(ui_SecondaryPhoneNumberInput, 10);
    lv_textarea_set_placeholder_text(ui_SecondaryPhoneNumberInput, "+90");

    ui_ProfilePagePasswordLabel = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_ProfilePagePasswordLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProfilePagePasswordLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ProfilePagePasswordLabel, 10);
    lv_obj_set_y(ui_ProfilePagePasswordLabel, 140);
    lv_label_set_text(ui_ProfilePagePasswordLabel, "Password");

    ui_ProfilePagePasswordInput = lv_textarea_create(ui_Container2);
    lv_obj_set_width(ui_ProfilePagePasswordInput, 200);
    lv_obj_set_height(ui_ProfilePagePasswordInput, 40);
    lv_obj_set_x(ui_ProfilePagePasswordInput, 10);
    lv_obj_set_y(ui_ProfilePagePasswordInput, 160);
    if("abcdefghijklmnopqrstuvwxyz0123456789!+%?-_*" == "") lv_textarea_set_accepted_chars(ui_ProfilePagePasswordInput,
                                                                                               NULL);
    else lv_textarea_set_accepted_chars(ui_ProfilePagePasswordInput, "abcdefghijklmnopqrstuvwxyz0123456789!+%?-_*");
    lv_textarea_set_max_length(ui_ProfilePagePasswordInput, 12);
    lv_textarea_set_placeholder_text(ui_ProfilePagePasswordInput, "Max 12 charachters");

    ui_ProfilePageSaveButton = lv_btn_create(ui_ProfilePage);
    lv_obj_set_width(ui_ProfilePageSaveButton, 100);
    lv_obj_set_height(ui_ProfilePageSaveButton, 50);
    lv_obj_set_x(ui_ProfilePageSaveButton, 0);
    lv_obj_set_y(ui_ProfilePageSaveButton, -40);
    lv_obj_set_align(ui_ProfilePageSaveButton, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ProfilePageSaveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ProfilePageSaveButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ProfilePageSaveButton, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProfilePageSaveButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProfilePageSaveButtonLabel = lv_label_create(ui_ProfilePageSaveButton);
    lv_obj_set_width(ui_ProfilePageSaveButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProfilePageSaveButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ProfilePageSaveButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProfilePageSaveButtonLabel, "Save");
    lv_obj_set_style_text_color(ui_ProfilePageSaveButtonLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProfilePageSaveButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProfilePageKeyboard = lv_keyboard_create(ui_ProfilePage);
    lv_obj_set_width(ui_ProfilePageKeyboard, 300);
    lv_obj_set_height(ui_ProfilePageKeyboard, 120);
    lv_obj_set_x(ui_ProfilePageKeyboard, 0);
    lv_obj_set_y(ui_ProfilePageKeyboard, -60);
    lv_obj_set_align(ui_ProfilePageKeyboard, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ProfilePageKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ProfilePageKeyboard1 = lv_keyboard_create(ui_ProfilePage);
    lv_obj_set_width(ui_ProfilePageKeyboard1, 300);
    lv_obj_set_height(ui_ProfilePageKeyboard1, 120);
    lv_obj_set_x(ui_ProfilePageKeyboard1, 0);
    lv_obj_set_y(ui_ProfilePageKeyboard1, -60);
    lv_obj_set_align(ui_ProfilePageKeyboard1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ProfilePageKeyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ProfilePageKeyboard2 = lv_keyboard_create(ui_ProfilePage);
    lv_obj_set_width(ui_ProfilePageKeyboard2, 300);
    lv_obj_set_height(ui_ProfilePageKeyboard2, 120);
    lv_obj_set_x(ui_ProfilePageKeyboard2, 0);
    lv_obj_set_y(ui_ProfilePageKeyboard2, -60);
    lv_obj_set_align(ui_ProfilePageKeyboard2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ProfilePageKeyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_PrimaryPhoneNumberInput, ui_event_PrimaryPhoneNumberInput, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SecondaryPhoneNumberInput, ui_event_SecondaryPhoneNumberInput, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ProfilePagePasswordInput, ui_event_ProfilePagePasswordInput, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ProfilePageSaveButton, ui_event_ProfilePageSaveButton, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_ProfilePageKeyboard, ui_PrimaryPhoneNumberInput);
    lv_keyboard_set_textarea(ui_ProfilePageKeyboard1, ui_SecondaryPhoneNumberInput);
    lv_keyboard_set_textarea(ui_ProfilePageKeyboard2, ui_ProfilePagePasswordInput);
    lv_obj_add_event_cb(ui_ProfilePage, ui_event_ProfilePage, LV_EVENT_ALL, NULL);

}
