// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_PredictionsPage_screen_init(void)
{
    ui_PredictionsPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PredictionsPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PredictionsPage, lv_color_hex(0xE6E6FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PredictionsPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PredictionTable = lv_obj_create(ui_PredictionsPage);
    lv_obj_remove_style_all(ui_PredictionTable);
    lv_obj_set_width(ui_PredictionTable, 280);
    lv_obj_set_height(ui_PredictionTable, 300);
    lv_obj_set_align(ui_PredictionTable, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PredictionTable, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PredictionTable, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PredictionTable, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PredictionTableHeaderRow = lv_obj_create(ui_PredictionTable);
    lv_obj_remove_style_all(ui_PredictionTableHeaderRow);
    lv_obj_set_width(ui_PredictionTableHeaderRow, 280);
    lv_obj_set_height(ui_PredictionTableHeaderRow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PredictionTableHeaderRow, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_PredictionTableHeaderRow, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PredictionTableHeaderRow, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PredictionTableHeaderRow, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PredictionTimeThLabel2 = lv_label_create(ui_PredictionTableHeaderRow);
    lv_obj_set_width(ui_PredictionTimeThLabel2, 56);
    lv_obj_set_height(ui_PredictionTimeThLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PredictionTimeThLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PredictionTimeThLabel2, "Time");
    lv_obj_set_style_text_align(ui_PredictionTimeThLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PredictionTimeThLabel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PredictionTimeThLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PredictionTimeThLabel2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AgeThLabel = lv_label_create(ui_PredictionTableHeaderRow);
    lv_obj_set_width(ui_AgeThLabel, 40);
    lv_obj_set_height(ui_AgeThLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AgeThLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AgeThLabel, "Age");
    lv_obj_set_style_text_align(ui_AgeThLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AgeThLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AgeThLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AgeThLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GenderThLabel = lv_label_create(ui_PredictionTableHeaderRow);
    lv_obj_set_width(ui_GenderThLabel, 60);
    lv_obj_set_height(ui_GenderThLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GenderThLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GenderThLabel, "Gender");
    lv_obj_set_style_text_align(ui_GenderThLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GenderThLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GenderThLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GenderThLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EmotionThLabel = lv_label_create(ui_PredictionTableHeaderRow);
    lv_obj_set_width(ui_EmotionThLabel, 70);
    lv_obj_set_height(ui_EmotionThLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_EmotionThLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EmotionThLabel, "Emotion");
    lv_obj_set_style_text_align(ui_EmotionThLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EmotionThLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EmotionThLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EmotionThLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EmotionThLabel1 = lv_label_create(ui_PredictionTableHeaderRow);
    lv_obj_set_width(ui_EmotionThLabel1, 54);
    lv_obj_set_height(ui_EmotionThLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_EmotionThLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EmotionThLabel1, "Result");
    lv_obj_set_style_text_align(ui_EmotionThLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EmotionThLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EmotionThLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EmotionThLabel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SamplingRateTableTitle2 = lv_label_create(ui_PredictionsPage);
    lv_obj_set_width(ui_SamplingRateTableTitle2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SamplingRateTableTitle2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SamplingRateTableTitle2, 0);
    lv_obj_set_y(ui_SamplingRateTableTitle2, 25);
    lv_obj_set_align(ui_SamplingRateTableTitle2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_SamplingRateTableTitle2, "Prediction Table");

    ui_BackButtonPredictionPage = lv_btn_create(ui_PredictionsPage);
    lv_obj_set_width(ui_BackButtonPredictionPage, 100);
    lv_obj_set_height(ui_BackButtonPredictionPage, 50);
    lv_obj_set_x(ui_BackButtonPredictionPage, 0);
    lv_obj_set_y(ui_BackButtonPredictionPage, -40);
    lv_obj_set_align(ui_BackButtonPredictionPage, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_BackButtonPredictionPage, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackButtonPredictionPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackButtonLabelPredictionPage = lv_label_create(ui_BackButtonPredictionPage);
    lv_obj_set_width(ui_BackButtonLabelPredictionPage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackButtonLabelPredictionPage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackButtonLabelPredictionPage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackButtonLabelPredictionPage, "Back");

    lv_obj_add_event_cb(ui_BackButtonPredictionPage, ui_event_BackButtonPredictionPage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PredictionsPage, ui_event_PredictionsPage, LV_EVENT_ALL, NULL);

}
