// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: UIDseign

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_DashboardScreen
void ui_DashboardScreen_screen_init(void);
lv_obj_t * ui_DashboardScreen;
void ui_event_SettingsButton(lv_event_t * e);
lv_obj_t * ui_SettingsButton;
lv_obj_t * ui_Label2;
lv_obj_t * ui_resultTable;
lv_obj_t * ui_header1;
lv_obj_t * ui_header2;
lv_obj_t * ui_header3;
lv_obj_t * ui_tablerow;
lv_obj_t * ui_rowcl1;
lv_obj_t * ui_rowcl2;
lv_obj_t * ui_rowcl3;
// CUSTOM VARIABLES

// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
lv_obj_t * ui_SettingsScreen;
lv_obj_t * ui_Container6;
lv_obj_t * ui_AppPasswordLabel;
lv_obj_t * ui_AppPasswordText;
lv_obj_t * ui_Parent1Phone;
lv_obj_t * ui_Parent1PhoneText;
lv_obj_t * ui_Parent2Phone;
lv_obj_t * ui_Parent2PhoneText;
void ui_event_SaveButton(lv_event_t * e);
lv_obj_t * ui_SaveButton;
lv_obj_t * ui_Label10;
void ui_event_BackButton(lv_event_t * e);
lv_obj_t * ui_BackButton;
lv_obj_t * ui_Label9;
// CUSTOM VARIABLES

// SCREEN: ui_Notification
void ui_Notification_screen_init(void);
void ui_event_Notification(lv_event_t * e);
lv_obj_t * ui_Notification;
void ui_event_Panel1(lv_event_t * e);
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_SettingsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 175, 0, &ui_SettingsScreen_screen_init);
    }
}

void ui_event_SaveButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Notification, LV_SCR_LOAD_ANIM_FADE_ON, 300, 100, &ui_Notification_screen_init);
    }
}

void ui_event_BackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DashboardScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 175, 0, &ui_DashboardScreen_screen_init);
    }
}

void ui_event_Notification(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_SettingsScreen_screen_init);
    }
}

void ui_event_Panel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_SettingsScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_DashboardScreen_screen_init();
    ui_SettingsScreen_screen_init();
    ui_Notification_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_DashboardScreen);
}
