// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: UIDseign

#ifndef _UIDSEIGN_UI_H
#define _UIDSEIGN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "LVGL_Driver.h"
#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_DashboardScreen
void ui_DashboardScreen_screen_init(void);
extern lv_obj_t * ui_DashboardScreen;
void ui_event_SettingsButton(lv_event_t * e);
extern lv_obj_t * ui_SettingsButton;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_resultTable;
extern lv_obj_t * ui_header1;
extern lv_obj_t * ui_header2;
extern lv_obj_t * ui_header3;
extern lv_obj_t * ui_tablerow;
extern lv_obj_t * ui_rowcl1;
extern lv_obj_t * ui_rowcl2;
extern lv_obj_t * ui_rowcl3;
// CUSTOM VARIABLES

// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
extern lv_obj_t * ui_SettingsScreen;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_AppPasswordLabel;
extern lv_obj_t * ui_AppPasswordText;
extern lv_obj_t * ui_Parent1Phone;
extern lv_obj_t * ui_Parent1PhoneText;
extern lv_obj_t * ui_Parent2Phone;
extern lv_obj_t * ui_Parent2PhoneText;
void ui_event_SaveButton(lv_event_t * e);
extern lv_obj_t * ui_SaveButton;
extern lv_obj_t * ui_Label10;
void ui_event_BackButton(lv_event_t * e);
extern lv_obj_t * ui_BackButton;
extern lv_obj_t * ui_Label9;
// CUSTOM VARIABLES

// SCREEN: ui_Notification
void ui_Notification_screen_init(void);
void ui_event_Notification(lv_event_t * e);
extern lv_obj_t * ui_Notification;
void ui_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
